### PR TITLE
[WIP] I76 authentication components

### LINKED ISSUE #29: add Nuxt to ESLint configs
## Basic Information
https://github.com/nuxt/eslint-config

## Other Information
N/A

### LINKED ISSUE #98: [BUG] Footer document flow is messed up
image

It's mean't to be at the bottom of the page.... Guess I can't code ;(

### PR DESCRIPTION
**Pull request by jsun1590**
## Change Summary
**[Briefly summarise the changes that you made. Just high-level stuff]**

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**
* Resolves #29 
* Resolves #98

### CODE REVIEW

**Review by otta8634 — APPROVED** [review]
@[otta8634](https://github.com/otta8634) told me to.

**Comment by otta8634** [comment]
> @[otta8634](https://github.com/otta8634) told me to.

Mistake, someone please delete the review

**Comment by jsun1590** [comment]
@codersforcauses/elucidate Does anyone know what's happening with this branch? Is this branch going to be merged eventually or just exists to share components?

**Comment by jsun1590** [comment]
Temporarily closed branch pending requirements

**Pull request closed without merging**
